services:
    api:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "8080:80"
        depends_on:
          - db

    db:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        container_name: local_sql_server2022
        ports:
          - "1433:1433"

        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "LocalPassword"